keys:
  - &u_purefn age1pgru95m33fze0a0mldracn08e8jer4mwujch9t8yax42evm69szq296j4n
  - &m_ronin age1uajv2qzzvv07742c540h59jf3k0dhdzwlzv0tqd2tstl5wq0d5sqj0zsn3
creation_rules:
  - path_regex: modules/sops/secrets.yaml
    key_groups:
    - age:
      - *u_purefn
      - *m_ronin

