# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
      <nixpkgs/nixos/modules/profiles/qemu-guest.nix>
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "ehci_pci" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  virtualisation.virtualbox.guest.enable = true;

  fileSystems."/" =
    { label = "nixos";
      fsType = "ext4";
    };

  fileSystems."/torrents" =
    { fsType = "vboxsf";
      device = "Torrents";
      options = "defaults,rw,uid=${toString config.ids.uids.transmission},gid=${toString config.ids.gids.transmission}";
    };

  swapDevices = [ ];

  nix.maxJobs = 1;
}
