#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Load resources
xrdb -merge .Xresources

xmodmap .Xmodmap

xbindkeys

# Set the background color
xsetroot -solid midnightblue

xsetroot -cursor_name left_ptr

xscreensaver -no-splash &

urxvtd -q -o -f

xcompmgr -n &

status-notifier-watcher &

taffybar &

nm-applet --sm-disable --indicator &

pasystray &

battery-monitor &

eval $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

export GTK_IM_MODULE="xim"

exec xmonad

# exec systemctl --user start wm.target
