#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Load resources
xrdb -merge .Xresources
 
# Set the background color<
xsetroot -solid midnightblue
 
xscreensaver -no-splash &

xmodmap .Xmodmap
 
xsetroot -cursor_name left_ptr

urxvtcd &

export GTK_IM_MODULE="xim"

exec dbus-launch xmonad

