#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

export LOCALE_ARCHIVE=/home/rwallace/.nix-profile/lib/locale/locale-archive

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Load resources
xrdb -merge .Xresources
 
# Set the background color<
xsetroot -solid midnightblue
 
xscreensaver -no-splash &

xmodmap .Xmodmap
 
xsetroot -cursor_name left_ptr

urxvtcd &

xcompmgr -n &

start-pulseaudio-x11

export GTK_IM_MODULE="xim"

exec dbus-launch --exit-with-session xmonad

