#!/bin/bash
 
# Load resources
 
xrdb -merge .Xresources
 
# Set the background color<
 
xsetroot -solid midnightblue
 
xscreensaver -no-splash &

xmodmap .Xmodmap
 
urxvtcd &

export GTK_IM_MODULE="xim"

exec xmonad

